#!/usr/bin/ruby
require 'fileutils'

include FileUtils

@src = "/Library/Application Support/Developer/Shared/Xcode/Project Templates/Application/iUnitTest Application"
@path = File.join(File.dirname(__FILE__), "../")

mkdir_p File.join(@path, "scripts")

src_file = File.join(@src, "scripts/update_iunittest.rb")
dst_file = File.join(@path, "scripts/update_iunittest.rb")
cp(src_file, dst_file) if File.exist? src_file

require 'scripts/update_iunittest'
